# .github/workflows/build_cv.yml
name: Build CV, Cover Letter, and References

on:
  push:
    branches:
      - '**'       # Triggers on all branches
  pull_request:
    branches:
      - '**'       # Triggers on PRs to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Allows the workflow to push back to the repository

      # 2. Detect Changed Files
      - name: Detect Changed Files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            preamble_tex:
              - 'preamble.tex'
            cv_tex:
              - 'cv.tex'
            cv_pdf:
              - 'cv.pdf'
            cover_letter_tex:
              - 'cover_letter.tex'
            cover_letter_pdf:
              - 'cover_letter.pdf'
            references_tex:
              - 'references.tex'
            references_pdf:
              - 'references.pdf'

      # 3. Install LaTeX and Dependencies (including optipng)
      - name: Install LaTeX and Dependencies
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.cover_letter_tex == 'true' || steps.filter.outputs.references_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ghostscript imagemagick poppler-utils texlive-xetex texlive-fonts-recommended texlive-latex-extra latexmk optipng

      # 4. Compile Monochrome CV (default)
      - name: Compile Monochrome CV
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 5. Compress Monochrome CV PDF
      - name: Compress Monochrome CV PDF
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cv_temp.pdf cv.pdf
          mv cv_temp.pdf cv.pdf

      # 6. Compile Colorful CV
      - name: Generate Colorful CV tex file
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          echo '\def\colorful{}\input{cv.tex}' > cv_colorful.tex

      - name: Compile Colorful CV
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_colorful.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 7. Compress Colorful CV PDF
      - name: Compress Colorful CV PDF
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cv_colorful_temp.pdf cv_colorful.pdf
          mv cv_colorful_temp.pdf cv_colorful.pdf

      # 8. Compile Monochrome Cover Letter (default)
      - name: Compile Monochrome Cover Letter
        if: ${{ steps.filter.outputs.cover_letter_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 9. Compress Monochrome Cover Letter PDF
      - name: Compress Monochrome Cover Letter PDF
        if: ${{ steps.filter.outputs.cover_letter_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cover_letter_temp.pdf cover_letter.pdf
          mv cover_letter_temp.pdf cover_letter.pdf

      # 10. Compile Colorful Cover Letter
      - name: Generate Colorful Cover Letter tex file
        if: ${{ steps.filter.outputs.cover_letter_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          echo '\def\colorful{}\input{cover_letter.tex}' > cover_letter_colorful.tex

      - name: Compile Colorful Cover Letter
        if: ${{ steps.filter.outputs.cover_letter_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter_colorful.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 11. Compress Colorful Cover Letter PDF
      - name: Compress Colorful Cover Letter PDF
        if: ${{ steps.filter.outputs.cover_letter_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cover_letter_colorful_temp.pdf cover_letter_colorful.pdf
          mv cover_letter_colorful_temp.pdf cover_letter_colorful.pdf

      # 12. Compile Monochrome References (default)
      - name: Compile Monochrome References
        if: ${{ steps.filter.outputs.references_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: references.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 13. Compress Monochrome References PDF
      - name: Compress Monochrome References PDF
        if: ${{ steps.filter.outputs.references_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=references_temp.pdf references.pdf
          mv references_temp.pdf references.pdf

      # 14. Compile Colorful References
      - name: Generate Colorful References tex file
        if: ${{ steps.filter.outputs.references_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          echo '\def\colorful{}\input{references.tex}' > references_colorful.tex

      - name: Compile Colorful References
        if: ${{ steps.filter.outputs.references_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        uses: xu-cheng/latex-action@v2
        with:
          root_file: references_colorful.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 15. Compress Colorful References PDF
      - name: Compress Colorful References PDF
        if: ${{ steps.filter.outputs.references_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' }}
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=references_colorful_temp.pdf references_colorful.pdf
          mv references_colorful_temp.pdf references_colorful.pdf

      # 16. Convert CV Colorful PDF to Image
      - name: Convert CV Colorful PDF to Image
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' || steps.filter.outputs.cv_pdf == 'true' }}
        run: |
          pdftoppm -png -f 1 -singlefile cv_colorful.pdf cv_colorful_thumbnail

      # 17. Compress CV Colorful Thumbnail Image
      - name: Compress CV Colorful Thumbnail Image
        if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' || steps.filter.outputs.cv_pdf == 'true' }}
        run: |
          mogrify -strip -resize 800x cv_colorful_thumbnail.png

      # Optional: Further Optimize Image with optipng
      # Uncomment the following step if you wish to further optimize the PNG image
      # - name: Optimize CV Colorful Thumbnail Image with optipng
      #   if: ${{ steps.filter.outputs.cv_tex == 'true' || steps.filter.outputs.preamble_tex == 'true' || steps.filter.outputs.cv_pdf == 'true' }}
      #   run: |
      #     optipng -o7 cv_images/cv_colorful_thumbnail.png

      # 18. Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 19. Determine PDFs and Images to Add
      - name: Determine PDFs and Images to Add
        id: to_add
        run: |
          TO_ADD=""
          # Monochrome CV
          if [ "${{ steps.filter.outputs.cv_tex }}" == "true" ] || [ "${{ steps.filter.outputs.preamble_tex }}" == "true" ]; then
            TO_ADD+=" cv.pdf cv_colorful.pdf cv_colorful_thumbnail.png"
          fi
          # Monochrome Cover Letter
          if [ "${{ steps.filter.outputs.cover_letter_tex }}" == "true" ] || [ "${{ steps.filter.outputs.preamble_tex }}" == "true" ]; then
            TO_ADD+=" cover_letter.pdf cover_letter_colorful.pdf"
          fi
          # Monochrome References
          if [ "${{ steps.filter.outputs.references_tex }}" == "true" ] || [ "${{ steps.filter.outputs.preamble_tex }}" == "true" ]; then
            TO_ADD+=" references.pdf references_colorful.pdf"
          fi
          echo "to_add=$TO_ADD" >> $GITHUB_ENV

      # 20. Add PDF and Image files to Git
      - name: Add PDF and Image files
        run: |
          if [ -n "${{ env.to_add }}" ]; then
            git add ${{ env.to_add }} cv_images/cv_colorful_thumbnail.png
          fi

      # 21. Commit PDFs and Images
      - name: Commit PDFs and Images
        run: |
          git commit -m "Update CV, Cover Letter, References PDFs, and Preview Image [skip ci]" || echo "No changes to commit"

      # 22. Push PDFs and Images
      - name: Push PDFs and Images
        run: |
          git push origin HEAD:${GITHUB_REF#refs/heads/}
