# .github/workflows/build_cv.yml
name: Build CV and Cover Letter

on:
  push:
    branches:
      - '**'       # Triggers on all branches
  pull_request:
    branches:
      - '**'       # Triggers on PRs to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2. Install LaTeX and Dependencies
      - name: Install LaTeX and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra latexmk ghostscript

      # 3. Compile Standard CV using latex-action@v2
      - name: Compile Standard CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 4. Generate Monochrome CV tex file
      - name: Generate Monochrome CV tex file
        run: |
          echo '\def\monochrome{}\def\excludephoto{}\input{cv.tex}' > cv_monochrome.tex

      # 5. Compile Monochrome CV using latex-action@v2
      - name: Compile Monochrome CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_monochrome.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 6. Compress Monochrome CV PDF
      - name: Compress Monochrome CV PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cv_monochrome_compressed.pdf cv_monochrome.pdf

      # 7. Compile Standard Cover Letter using latex-action@v2
      - name: Compile Standard Cover Letter
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 8. Generate Monochrome Cover Letter tex file
      - name: Generate Monochrome Cover Letter tex file
        run: |
          echo '\def\monochrome{}\def\excludephoto{}\input{cover_letter.tex}' > cover_letter_monochrome.tex

      # 9. Compile Monochrome Cover Letter using latex-action@v2
      - name: Compile Monochrome Cover Letter
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter_monochrome.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 10. Compress Monochrome Cover Letter PDF
      - name: Compress Monochrome Cover Letter PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cover_letter_monochrome_compressed.pdf cover_letter_monochrome.pdf

      # 11. Compile Standard References using latex-action@v2
      - name: Compile Standard References
        uses: xu-cheng/latex-action@v2
        with:
          root_file: references.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 12. Generate Monochrome References tex file
      - name: Generate Monochrome References tex file
        run: |
          echo '\def\monochrome{}\def\excludephoto{}\input{references.tex}' > references_monochrome.tex

      # 13. Compile Monochrome References using latex-action@v2
      - name: Compile Monochrome References
        uses: xu-cheng/latex-action@v2
        with:
          root_file: references_monochrome.tex
          compiler: 'latexmk'
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true

      # 14. Compress Monochrome References PDF
      - name: Compress Monochrome References PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=references_monochrome_compressed.pdf references_monochrome.pdf

      # 15. Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 16. Add PDF files to Git
      - name: Add PDF files
        run: |
          git add cv.pdf cover_letter.pdf references.pdf \
                  cv_monochrome_compressed.pdf cover_letter_monochrome_compressed.pdf references_monochrome_compressed.pdf

      # 17. Commit changes
      - name: Commit PDFs
        run: |
          git commit -m "Update CV, Cover Letter, and References PDFs [skip ci]" || echo "No changes to commit"

      # 18. Push changes
      - name: Push PDFs
        run: |
          git push origin HEAD:${GITHUB_REF#refs/heads/}