# .github/workflows/build_cv.yml
name: Build CV and Cover Letter

on:
  push:
    branches:
      - '**'       # Triggers on all branches
  pull_request:
    branches:
      - '**'       # Triggers on PRs to any branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install LaTeX and Dependencies
      - name: Install LaTeX and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-latex-extra latexmk ghostscript

      # 3. Compile Standard CV using latex-action@v2
      - name: Compile Standard CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 4. Generate Monochrome CV tex file
      - name: Generate Monochrome CV tex file
        run: |
          echo '\def\monochrome{}\def\includephoto{}\input{cv.tex}' > cv_monochrome.tex

      # 5. Compile Monochrome CV using latex-action@v2
      - name: Compile Monochrome CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_monochrome.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 6. Compress Monochrome CV PDF
      - name: Compress Monochrome CV PDF
        run: |
          if [ -f "cv_monochrome.pdf" ]; then
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
               -dNOPAUSE -dQUIET -dBATCH \
               -sOutputFile=cv_monochrome_compressed.pdf cv_monochrome.pdf
          else
            echo "Monochrome CV PDF not found. Skipping compression."
          fi

      # 7. Compile Standard Cover Letter using latex-action@v2
      - name: Compile Standard Cover Letter
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 8. Generate Monochrome Cover Letter tex file
      - name: Generate Monochrome Cover Letter tex file
        run: |
          echo '\def\monochrome{}\def\includephoto{}\input{cover_letter.tex}' > cover_letter_monochrome.tex

      # 9. Compile Monochrome Cover Letter using latex-action@v2
      - name: Compile Monochrome Cover Letter
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter_monochrome.tex
          compiler: 'latexmk'  # Use latexmk as the compiler
          args: "-xelatex -nobibtex -f -synctex=1 -interaction=nonstopmode -file-line-error -outdir=."
        continue-on-error: true  # Continue workflow even if this step fails

      # 10. Compress Monochrome Cover Letter PDF
      - name: Compress Monochrome Cover Letter PDF
        run: |
          if [ -f "cover_letter_monochrome.pdf" ]; then
            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
               -dNOPAUSE -dQUIET -dBATCH \
               -sOutputFile=cover_letter_monochrome_compressed.pdf cover_letter_monochrome.pdf
          else
            echo "Monochrome Cover Letter PDF not found. Skipping compression."
          fi

      # 11. Upload Standard CV PDF
      - name: Upload Standard CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: Standard-CV-PDF
          path: |
            cv.pdf

      # 12. Upload Monochrome Compressed CV PDF
      - name: Upload Monochrome Compressed CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: Monochrome-Compressed-CV-PDF
          path: |
            cv_monochrome_compressed.pdf

      # 13. Upload Standard Cover Letter PDF
      - name: Upload Standard Cover Letter PDF
        uses: actions/upload-artifact@v3
        with:
          name: Standard-Cover-Letter-PDF
          path: |
            cover_letter.pdf

      # 14. Upload Monochrome Compressed Cover Letter PDF
      - name: Upload Monochrome Compressed Cover Letter PDF
        uses: actions/upload-artifact@v3
        with:
          name: Monochrome-Compressed-Cover-Letter-PDF
          path: |
            cover_letter_monochrome_compressed.pdf