# .github/workflows/build_cv.yml
name: Build CV and Cover Letter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up LaTeX using latex-action@v2
      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          compiler: 'xelatex'

      # 3. Install Ghostscript
      - name: Install Ghostscript
        run: sudo apt-get update && sudo apt-get install -y ghostscript

      # 4. Compile Standard CV
      - name: Compile Standard CV
        run: |
          latexmk -xelatex -synctex=1 -interaction=nonstopmode -file-line-error -outdir=. cv.tex

      # 5. Compile Monochrome CV
      - name: Compile Monochrome CV
        run: |
          latexmk -xelatex '\def\monochrome{}\def\includephoto{} \input{cv.tex} -jobname=cv_monochrome' -synctex=1 -interaction=nonstopmode -file-line-error -outdir=. cv.tex

      # 6. Compress Monochrome CV PDF
      - name: Compress Monochrome CV PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cv_monochrome_compressed.pdf cv_monochrome.pdf

      # 7. Compile Standard Cover Letter
      - name: Compile Standard Cover Letter
        run: |
          latexmk -xelatex -synctex=1 -interaction=nonstopmode -file-line-error -outdir=. cover_letter.tex

      # 8. Compile Monochrome Cover Letter
      - name: Compile Monochrome Cover Letter
        run: |
          latexmk -xelatex '\def\monochrome{}\def\includephoto{} \input{cover_letter.tex} -jobname=cover_letter_monochrome' -synctex=1 -interaction=nonstopmode -file-line-error -outdir=. cover_letter.tex

      # 9. Compress Monochrome Cover Letter PDF
      - name: Compress Monochrome Cover Letter PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cover_letter_monochrome_compressed.pdf cover_letter_monochrome.pdf

      # 10. Upload Standard CV PDF
      - name: Upload Standard CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: Standard-CV-PDF
          path: |
            cv.pdf

      # 11. Upload Monochrome Compressed CV PDF
      - name: Upload Monochrome Compressed CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: Monochrome-Compressed-CV-PDF
          path: |
            cv_monochrome_compressed.pdf

      # 12. Upload Standard Cover Letter PDF
      - name: Upload Standard Cover Letter PDF
        uses: actions/upload-artifact@v3
        with:
          name: Standard-Cover-Letter-PDF
          path: |
            cover_letter.pdf

      # 13. Upload Monochrome Compressed Cover Letter PDF
      - name: Upload Monochrome Compressed Cover Letter PDF
        uses: actions/upload-artifact@v3
        with:
          name: Monochrome-Compressed-Cover-Letter-PDF
          path: |
            cover_letter_monochrome_compressed.pdf
