# .github/workflows/build_cv.yml
name: Build CV and Cover Letter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Compile Standard CV using latex-action
      - name: Compile Standard CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          compiler: 'xelatex'

      # 3. Compile Monochrome CV using latex-action
      - name: Compile Monochrome CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
          compiler: 'xelatex'
          args: "\def\monochrome{}\def\includephoto{} \input{cv.tex} -jobname=cv_monochrome"

      # 4. Compress Monochrome CV PDF
      - name: Compress Monochrome CV PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cv_monochrome_compressed.pdf cv_monochrome.pdf

      # 5. Compile Standard Cover Letter using latex-action
      - name: Compile Standard Cover Letter
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter.tex
          compiler: 'xelatex'

      # 6. Compile Monochrome Cover Letter using latex-action
      - name: Compile Monochrome Cover Letter
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cover_letter.tex
          compiler: 'xelatex'
          args: "\def\monochrome{}\def\includephoto{} \input{cover_letter.tex} -jobname=cover_letter_monochrome"

      # 7. Compress Monochrome Cover Letter PDF
      - name: Compress Monochrome Cover Letter PDF
        run: |
          gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook \
             -dNOPAUSE -dQUIET -dBATCH \
             -sOutputFile=cover_letter_monochrome_compressed.pdf cover_letter_monochrome.pdf

      # 8. Upload Standard CV PDF
      - name: Upload Standard CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: Standard-CV-PDF
          path: |
            cv.pdf

      # 9. Upload Monochrome Compressed CV PDF
      - name: Upload Monochrome Compressed CV PDF
        uses: actions/upload-artifact@v3
        with:
          name: Monochrome-Compressed-CV-PDF
          path: |
            cv_monochrome_compressed.pdf

      # 10. Upload Standard Cover Letter PDF
      - name: Upload Standard Cover Letter PDF
        uses: actions/upload-artifact@v3
        with:
          name: Standard-Cover-Letter-PDF
          path: |
            cover_letter.pdf

      # 11. Upload Monochrome Compressed Cover Letter PDF
      - name: Upload Monochrome Compressed Cover Letter PDF
        uses: actions/upload-artifact@v3
        with:
          name: Monochrome-Compressed-Cover-Letter-PDF
          path: |
            cover_letter_monochrome_compressed.pdf
